FROM golang:1.18 as runner

WORKDIR /app

COPY ../go.mod ./
COPY ../go.sum ./

RUN go mod download
RUN go install github.com/cosmtrek/air@latest

COPY .. ./
COPY ../.env .

EXPOSE 80
ENTRYPOINT ["/go/bin/air"]
