version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for backend_service Go Module.
  - package-ecosystem: gomod
    directory: /backend_service
    schedule:
      interval: daily

  # Maintain dependencies for mongo_service Go Module.
  - package-ecosystem: gomod
    directory: /mongo_service
    schedule:
      interval: daily

  # Maintain dependencies for postgres_service Go Module.
  - package-ecosystem: gomod
    directory: /postgres_service
    schedule:
      interval: daily

  # Maintain dependencies for web.
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: daily
