run:
  issues-exit-code: 1
  allow-parallel-runners: true

  skip-dirs:
    - "proto"

  skip-files:
    - "pkg/adapter/resolver/resolver.go"
    - "pkg/adapter/resolver/schema.resolvers.go"

linters:
  enable-all: true
  disable:
    # deprecated (since v1.38.0)
    - scopelint
    # deprecated (since v1.41.0)
    - golint
    # deprecated (since v1.38.0)
    - interfacer
    # deprecated (since v1.38.0)
    - maligned
    # irrelevant
    - goerr113
    # using goimports-reviser
    - gci

issues:
  fix: true
  exclude-rules:
    - linters:
        - lll
      # ignore imports and comments
      source: '"github.com/kucera-lukas/micro-backends|//'

linters-settings:
  lll:
    line-length: 80
