repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.2
    hooks:
      - id: clang-format
        files: \.(proto)$

  - repo: https://github.com/segmentio/golines
    rev: v0.12.2
    hooks:
      - id: golines
        entry: golines -w --max-len=80 .

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml|graphql|graphqls)$
        entry: prettier --write --list-different
