name: Continuous Integration

on: [push]

jobs:
  format:
    name: format
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Format Go files
        run: make fmt

      - name: Exit If Git Diff
        run: |
          chmod +x ./scripts/exit_if_diff.sh
          ./scripts/exit_if_diff.sh

  lint:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workdir: [backend_service, mongo_service, postgres_service]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Lint ${{ matrix.workdir }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.workdir }}
