name: Continuous Integration

on: [push]

jobs:
  server:
    name: server
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend_service

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: mongo_service

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: postgres_service

      - name: Make fmt
        run: make fmt

      - name: Exit If Git Diff
        run: |
          chmod +x ./scripts/exit_if_diff.sh
          ./scripts/exit_if_diff.sh
